# api_id and api_hash can be obtained from https://my.telegram.org
# bot_token can be obtained from https://t.me/botfather
# session_string can be obtained from https://repl.it/@subinps/GenerateStringSession
# sudo_users can be obtained from https://t.me/userinfobot

[pyrogram]
api_id =  23903140                                                    # required
api_hash = " 579f1bcf3eac1660d81ef34b09906012"                       # required
bot_token = "8568135601:AAEkErD59mkXahX-HMpJRGEzgJIMHaWtThE"                  # either bot_token or session_string is required
session_string = "1BVtsOKEBuz6czcGFeSWqgxnNtR1mgs9COyh34lqA5U4HVuyvmb2p3L9g-96sIgU7BR96o-cMVlYIJvkPBYoxDUg8I_lick9K2x98_HXgLBl5jKoth3GqrL16bt_HUnq5Qvt7ReZ4EeVFioEYklVNJSEZewlHIh9II7Ob6Js-rMrihhalSmPKM4Da6IAAX91kSaL72mUjj1sbeV85rb-OY_2HeNJY7H2_vQmI0VjWsoirpNNytQEDwrfONEFQbtqYXtwkkcvhePRb6ihxHkpFKx0NIKZbK_MTEE37KTsU9RMUI4pxQnuNRAxfXQpZIAaTOCdELByTfsMGzBacEQ44A3wLBrNjNX4=" # either bot_token or session_string is required
sudo_users = [1416433622]                                 # optional


# chat ids can be obtained from https://t.me/getidsbot
# All chats must be in the format of [-]1001234567890
# You can add multiple chats in the format of a list
# You can also add multiple chats in the format of a list of lists
# Atleast one chat must be added

[[chats]]
from = -100123456789        # required
to = 123456789              # required
replace = { "old" = "new" } # optional

[[chats]]
from = [123456789, -100123456789]               # required
to = 123456789                                  # required
replace = { "only_apply_to_this_chat" = "new" } # optional

[[chats]]
from = -100123456789            # required
to = [123456789, -100123456789] # required

[[chats]]
from = [123456789, -100123456789] # required
to = [123456789, -100123456789]   # required
